// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvzoswqduhpeynfqwjzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2em9zd3FkdWhwZXluZnF3anpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTA4NzMsImV4cCI6MjA2ODg2Njg3M30.xT1cXbQzq1ZmLJ8RcEMTMmr20XSHLM2vwIBxqWJ2uag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});